services:
  3xui:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: 3xui_app
    volumes:
      - $PWD/db/:/etc/x-ui/
      - $PWD/cert/:/root/cert/
    environment:
      XRAY_VMESS_AEAD_FORCED: "false"
      XUI_ENABLE_FAIL2BAN: "true"
    tty: true
    restart: unless-stopped

    labels:
      - traefik.enable=true
      - "traefik.http.services.3xui.loadbalancer.server.port=2053"      # 容器内部实际端口
      - "traefik.http.services.3xui.loadbalancer.server.scheme=http"
      - "traefik.http.routers.https-0-dwdtlsmw34ky2tl3e0v4zgk3-3xui.service=3xui"
      - "traefik.http.routers.http-0-dwdtlsmw34ky2tl3e0v4zgk3-3xui.service=3xui"
